# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    setup_ci if is_ci

    match(type: "development", 
      readonly: is_ci || true)

    update_code_signing_settings(
      code_sign_identity: "Apple Development",
      use_automatic_signing: false,
      path: "Quest Tracker.xcodeproj",
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.gmail.mdzawodniak.Quest-Tracker"]
      )
    
    build_app(scheme: "Quest Tracker", export_method: 'development')
    
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Quest Tracker.xcodeproj",
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.gmail.mdzawodniak.Quest-Tracker"]
      )

  end

desc "release_build"
  lane :release do
    setup_ci if is_ci

    match(type: "appstore", 
      readonly: is_ci || true)

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT']
    )

    update_code_signing_settings(
      code_sign_identity: "Apple Distribution",
      use_automatic_signing: false,
      path: "Quest Tracker.xcodeproj",
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.gmail.mdzawodniak.Quest-Tracker"]
      )

    build_app(scheme: "Quest Tracker", export_method: 'app-store')

    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true,
      skip_metadata: false,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
      )

  update_code_signing_settings(
    code_sign_identity: "Apple Development",
    use_automatic_signing: true,
    path: "Quest Tracker.xcodeproj",
    profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.gmail.mdzawodniak.Quest-Tracker"]
    )

    sentry_debug_files_upload(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: "matt-zawodniak",
      project_slug: "quest-tracker",
    )

  end

end
