name: PR
on:
  pull_request:

jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.0.1

      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: Create basic auth
        id: basic_auth
        run : |
          echo "basic_token=$(echo 'matt-zawodniak:${{ secrets.MATCH_PAT }}' | base64)" >> "$GITHUB_OUTPUT"

          echo "${{ secrets.MATCH_PAT }}" | base64
      
      
      - name: Build App
        run: |
          echo "token: ${{steps.basic_auth.outputs.basic_token}}"
          bundle install
          bundle exec fastlane build
   
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_SSH_KEY }}

      - name: Upload app-store ipa and dsyms to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-store ipa & dsyms
          path: |
            *.ipa
            *.app.dSYM.zip