name: release
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2

      - name: Checkout repository
        uses: actions/checkout@v4
     
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.160.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      
      - name: Build App
        run: |
          echo "${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}" | base64
          bundle install
          bundle exec fastlane release
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_SSH_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  #        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

      - name: Upload ipa and dsyms to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ipa & dsyms
          path: |
            *.ipa
            *.app.dSYM.zip

      - name: Upload logs to artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            /Users/runner/Library/Logs/gym/*.log

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags
      - name: GitHub Action for SwiftLint
        #Don't trust rando code on internet. Pin to a SHA so they can't rugpull you
        uses: yannpom/action-swiftlint@ae462bc2d8f56fc8564d9bae917bb230689d9644 
        env:
          DIFF_BASE: ${{ github.base_ref }}
        with:
          args: --strict
